moves memory issues to troubleshooting
gazebosim/docs pull request #255
Opened 2022-06-27 11:29 UTC by onurtore

Sequential execution moved to troubleshooting.

2022-06-27 11:30 UTC, onurtore commented
@chapulina ,
When I reviewed my last effort, it looks like this way better. What do you think?

2022-06-27 18:13 UTC, onurtore commented
Fixed the typo for all supported versions.

2022-06-27 20:18 UTC, chapulina requested changes

2022-06-28 08:13 UTC, onurtore commented on garden/troubleshooting.md
> +# Troubleshooting
Done

2022-06-29 16:49 UTC, chapulina approved these changes

2022-06-29 16:49 UTC, merged