Style and other improvements for get_started and ros_installation
gazebosim/docs pull request #343
Opened 2023-02-22 17:39 UTC by j-rivero

One fix or improvement per commit:

- Use warning div for ROS note
- Add Windows to the table of distros
- Fix old gazebo classic reference
- Use plain bold style
- Improve header description
- Clarify URL for osrfoundation repo

2023-02-22 23:08 UTC, kscottz requested changes
Made a few suggestions. Toss those in and this can be merged.

2023-02-22 23:08 UTC, kscottz commented on get_started.md
> +| Windows | Support via conda-forge is not fully functional, there are known runtime problems [Gazebo for Windows Issue](https://github.com/gazebosim/gz-sim/issues/168).
```suggestion
| Windows | Support via Conda-Forge is not fully functional, as there are known runtime issues [see this issue for details](https://github.com/gazebosim/gz-sim/issues/168).
```

2023-02-22 23:08 UTC, kscottz commented on ros_installation.md
> +to get the Gazebo binary packages it can be installed from the ROS
```suggestion
to get the Gazebo binary packages, it can be installed from the ROS
```

2023-03-01 17:32 UTC, j-rivero commented
> Made a few suggestions. Toss those in and this can be merged.

Thanks Kat!

2023-03-01 17:33 UTC, merged